### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by volkerku** [fabio914/OculusQuestMixedRealityForiOS#11]
Xcode 12.1

/Users/xxx/Library/Developer/Xcode/DerivedData/RealityMixer-aebctrqcpjdoizcknkfjddsoinrz/Build/Intermediates.noindex/RealityMixer.build/Debug-iphoneos/RealityMixer.build/Script-A328D8C6253C8CE200B90E62.sh: line 2: carthage: command not found
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by fabio914** [comment]
You can follow [these instructions](https://github.com/Carthage/Carthage#installing-carthage) to install Carthage.

**Comment by volkerku** [comment]
Thanks you. 
I managed to compile for my new iPhone 12 Pro with LiDAR.
Need to play more to figure out how it works. I guess I need to connect the iPhone to an external screen to see the camera image while calibrating.
v.

Volker Kuchelmeister
Research Fellow Immersive Visualisation
UNSW felt Experience and Empathy Lab (feel)

UNSW Art & Design, Sydney
 
Paddington Campus
Cnr Oxford St & Greens Rd,  
Paddington, NSW 2021 
Australia 
 
M:  	+61 (0)417 257 787
E:  	kuchel@unsw.edu.au <mailto:kuchel@unsw.edu.au>
W: 	http://kuchelmeister.net <http://kuchelmeister.net/>

**Comment by fabio914** [comment]
Hmmm, not necessarily. You'll only need to look at the screen for the third step of the calibration. 

For the first step you'll only need to bring the right controller's trigger button as close as possible to the camera and then press the trigger. Then on the second step you can move away from the camera (about 1.5m) and then press the right controller's trigger button a second time while you're facing the camera.

Now you can put your headset aside and look at the screen. You'll have to move the blue circle to where the right controller is on the photo.

Then on the last step you can try to look at the screen while wearing the headset to check the calibration, but you could instead just tap on "Save to Headset".

Now you can launch a compatible VR game/application on the Quest, start a screen recording on your iPhone, and start the mixed reality capture on the app.

I'm planning to write some better instructions and add them to the `Instructions.md` file, btw.
