### ISSUE TITLE
Rift S support

### ISSUE THREAD

**Issue by Kunstbanause** [fabio914/OculusQuestMixedRealityForiOS#16]
Sorry for the dumb question, but does this or could it support the Rift S. Or is it not needed at all? I am still pretty confused what the state of mixed reality without green screen is.

**Comment by fabio914** [comment]
This won't work with the Rift S as it is now, although the Oculus Mixed Reality Capture mechanism on the Rift S appears to be very similar to that of the Quest, so it might be possible to make some changes to make it work.

For now, I'd suggest using the [LIV](https://liv.tv) mixed reality software with the [LIV Camera app for iOS](https://apps.apple.com/br/app/liv-camera/id1482671526?l=en) to be able to use your iPhone/iPad to record mixed reality videos from the Rift S without a green screen. This won't really work exactly like my app, but the result will look very similar. I hope this helps.

**Comment by Kunstbanause** [comment]
Thanks so much for your detailed response. Will try the liv way ;)
