### ISSUE TITLE
Request to work on UI

### ISSUE THREAD

**Issue by noobyogi0010** [fabio914/OculusQuestMixedRealityForiOS#2]
Hi!
I would love to work on the UI. Can you please guide me on what is needed for the UI part?
Thanks.

**Comment by fabio914** [comment]
Hi, I just finished adding all the screens I was planning to add to this first version. Feel free to fork the project and make changes to the UI. I can then take a look and if they're good we can integrate some of these changes into the project.

**Comment by noobyogi0010** [comment]
@fabio914 Okay thanks!
