### ISSUE TITLE
Cannot use iPhone 11 Pro Max

### ISSUE THREAD

**Issue by catid** [fabio914/OculusQuestMixedRealityForiOS#22]
The "Connect" button is off the bottom of the screen so cannot start the live stream

**Comment by fabio914** [comment]
You should be able to scroll down to reach that button.

**Comment by catid** [comment]
Negative scroll is not functional

**Comment by fabio914** [comment]
Try scrolling from the center of the screen, that scroll view isn't using the whole width of the screen.

**Comment by catid** [comment]
Was able to get it to scroll with your hint.  Now the Connect button does not work.  The mixed reality calibration step worked properly:

![image](https://user-images.githubusercontent.com/252193/100576026-1d1d3700-3292-11eb-9d73-b22575961389.png)

Maybe it's because I haven't launched a game yet but the error is really vague

**Comment by catid** [comment]
Beat Saber has a MRC option to enable.  After it is enabled this error is still displayed.  Tried restarting the game and going into other game screens.

**Comment by fabio914** [comment]
Try calibrating again and then try to start the connection with Beat Saber after that. Also, make sure that you have given permission to the app to access your local network.

**Comment by catid** [comment]
The latest version seems to have resolved this
