### ISSUE TITLE
iPhone 11 Pro Max not working

### ISSUE THREAD

**Issue by allanwebix** [fabio914/OculusQuestMixedRealityForiOS#23]
It is connected but only shows blank screen.

**Comment by fabio914** [comment]
This is normal, put your headset on and continue playing and you'll see that the app will start displaying the right thing. Also, make sure that you've launched your VR game/app on the Quest before starting the connection.

**Comment by allanwebix** [comment]
I will do that, run first the Quest game and then start Mixed reality

**Comment by allanwebix** [comment]
All good but it seems my calibration is not properly set as the screen don't update.
