### ISSUE TITLE
Autofocus issues

### ISSUE THREAD

**Issue by Morendil** [fabio914/OculusQuestMixedRealityForiOS#34]
I'm shooting some experimental videos for the game PecoPeco, e.g. https://keybase.pub/morendil/PecoDev.mp4

As can be seen in video there are jumps in focus. How might I disable autofocus in Reality Mixer ? I can't access the camera controls from the app…

**Comment by jonathanperret** [comment]
I don't have the required hardware to run the app unfortunately, but according to the Apple docs, https://github.com/fabio914/OculusQuestMixedRealityForiOS/commit/3fe6bc04bb7c78572dcc7fee4893a2f54b4d30aa should disable autofocus? Maybe worth a try…

**Comment by fabio914** [comment]
I think @jonathanperret's suggestion works, I can open a PR adding an option to disable auto focus.
