### ISSUE TITLE
Unable to connect: connectionTimeout

### ISSUE THREAD

**Issue by 0408sea** [fabio914/OculusQuestMixedRealityForiOS#39]
When I try to calibrate it shows this message Unable to connect: connectionTimeout. 
![F825A10B-6336-49F7-AA53-E7A3FCB98B7D](https://user-images.githubusercontent.com/77823676/105450265-1a164580-5c48-11eb-9f81-80ac7ed74aa6.jpeg)

**Comment by fabio914** [comment]
Make sure that the Quest is running the Oculus Mixed Reality Capture app and that you've given permissions for the app to access your local network:

![IMG_7E58664FDDD8-1](https://user-images.githubusercontent.com/2430631/105596049-8057b100-5d8b-11eb-8423-e10c2b58df35.jpeg)

You might also need to review your network/router settings, to ensure that there's nothing preventing your devices from communicating with eachother.

**Comment by 0408sea** [comment]
If I can ping my quest 2 from my iPhone does that mean they can communicate to each other?

**Comment by 0408sea** [comment]
If I can ping my quest 2 using my iPhone does that mean they can communicate to each other?

**Comment by 0408sea** [comment]
Idk what happened, but my quest 2 somehow just changed it’s IP address today and when I try the new IP address it worked!
